spring.application.name=project-tracking-system
spring.profiles.active=dev
spring.jpa.hibernate.ddl-auto=update
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# Company Information
company.name=Aardvark Insurance Assessors
company.address=Galway, Ireland
company.phone=+353 85 123 4567
company.email=info@aardvark.ie