spring.application.name=project-tracking-system
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# Company Information
company.name=Aardvark Insurance Assessors
company.address=Galway, Ireland
company.phone=+353 85 123 4567
company.email=info@aardvark.ie

# Datasource
spring.datasource.url=jdbc:mysql://localhost:3306/project_tracking_system
spring.datasource.username=your_mysql_username
spring.datasource.password=your_mysql_password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate

# Flyway
spring.flyway.enabled=true